site_name: Curso de Programacao Orientada a Objetos
site_description: Trilha de POO para Engenharia com C++ e Python
site_url: ""
repo_url: ""
repo_name: ""

theme:
  name: material
  language: pt-BR
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy

plugins:
  - search
  - mkdocs-video

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - tables
  - toc:
      permalink: true

exclude_docs: |
  plano_de_implementacao.md
  referencias.md
  avaliacoes/
  guias_operacionais/
  projeto_integrador/

nav:
  - Inicio: index.md
  - 01. Fundamentos Git e IDE: fundamentos_git_ide/index.md
  - 02. Fundamentos de POO em C++ e Python: fundamentos_poo_cpp_python/index.md
  - 03. UML e Diagrama de Classes: modelagem_analise_codigo/index.md
  - 04. Sobrecarga de Construtores em C++: fundamentos_poo_cpp_python/03_sobrecarga_construtores/index.md
  - 05. Acesso, Encapsulamento e Heranca em C++: fundamentos_poo_cpp_python/04_encapsulamento_heranca/index.md
  - 06. Polimorfismo em C++: fundamentos_poo_cpp_python/05_polimorfismo/index.md
